#!/usr/bin/python3
# -*- coding: utf-8 -*-
riven_attr = {
    'Damage': {'label': '伤害', 'full_name': 'Damage', 'negative': True},
    'Multishot': {'label': '多重射击', 'full_name': 'Multishot', 'negative': True},
    'Speed': {'label': '攻速', 'full_name': 'Fire Rate / Attack Speed', 'negative': True},
    'Corpus': {'label': '对C系伤害', 'full_name': 'Damage to Corpus', 'negative': True},
    'Grineer': {'label': '对G系伤害', 'full_name': 'Damage to Grineer', 'negative': True},
    'Infested': {'label': '对I系伤害', 'full_name': 'Damage to Infested', 'negative': True},
    'Impact': {'label': '冲击伤害', 'full_name': 'Impact', 'negative': True},
    'Puncture': {'label': '穿刺伤害', 'full_name': 'Puncture', 'negative': True},
    'Slash': {'label': '切割伤害', 'full_name': 'Slash', 'negative': True},
    'Cold': {'label': '冰冻伤害', 'full_name': 'Cold', 'negative': True},
    'Heat': {'label': '火焰伤害', 'full_name': 'Heat', 'negative': True},
    'Toxin': {'label': '毒素伤害', 'full_name': 'Toxin', 'negative': True},
    'Electric': {'label': '电击伤害', 'full_name': 'Electric', 'negative': True},
    'ChannelDmg': {'label': '近战伤害', 'full_name': 'Channeling Damage', 'negative': True},
    'ChannelEff': {'label': '引导效率', 'full_name': 'Channeling Efficiency', 'negative': True},
    'Combo': {'label': '连击时间', 'full_name': 'Combo Duration', 'negative': True},
    'CritChance': {'label': '暴击几率', 'full_name': 'Critical Chance', 'negative': True},
    'Slide': {'label': '滑暴几率', 'full_name': 'Slide Attack Critical Chance', 'negative': True},
    'CritDmg': {'label': '暴击伤害', 'full_name': 'Critical Damage', 'negative': True},
    'Finisher': {'label': '处决伤害', 'full_name': 'Finisher Damage', 'negative': True},
    'Flight': {'label': '弹道飞行速度', 'full_name': 'Flight Speed', 'negative': True},
    'Ammo': {'label': '弹药最大量', 'full_name': 'Ammo Max', 'negative': True},
    'Magazine': {'label': '弹夹容量', 'full_name': 'Magazine Capacity', 'negative': True},
    'Punch': {'label': '穿透', 'full_name': 'Punch Through', 'negative': True},
    'Reload': {'label': '装填速度', 'full_name': 'Reload Speed', 'negative': True},
    'Range': {'label': '范围', 'full_name': 'Range', 'negative': True},
    'StatusC': {'label': '触发几率', 'full_name': 'Status Chance', 'negative': True},
    'Recoil': {'label': '后坐力', 'full_name': 'Weapon Recoil', 'negative': True},
    'StatusD': {'label': '触发持续时间', 'full_name': 'Status Duration', 'negative': True},
    'Zoom': {'label': '变焦', 'full_name': 'Zoom', 'negative': True},
}
